version: '3'
services:
  dns:
    image: jpillora/dnsmasq
    # ports:
    #   - 53:53/udp
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      - 'HTTP_USER=foo'
      - 'HTTP_PASS=bar'
    labels:
      - 'traefik.http.routers.dnsmasq.tls=true'
      - 'traefik.http.routers.dnsmasq.rule=HostRegexp(`dnsmasq.docker.internal`)'
      - 'traefik.http.routers.dnsmasq.entrypoints=websecure'
      - 'traefik.http.services.dnsmasq-service.loadbalancer.server.port=8080'

networks:
  default:
    external: true
    name: devops
