version: '2'
services:
  nexus3:
    # restart: always
    image: sonatype/nexus3:latest
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
    volumes:
      - nexus-data:/nexus-data
      - nexus-blob:/nexus-data/blobs
    # ports:
    #   - 8081:8081/tcp
    networks:
      - devops
  nginx:
    # restart: always
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 80:80/tcp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nexus.tls=true'
      - 'traefik.http.routers.nexus.rule=Host(`nexus.docker.internal`)'
      - 'traefik.http.routers.nexus.entrypoints=websecure'
      - 'traefik.docker.network=devops'
    networks:
      - devops

networks:
  devops:
    external: true

volumes:
  nexus-data: {}
  nexus-blob: {}
