version: '2'
services:
  nexus3:
    # restart: always
    image: sonatype/nexus3:latest
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
    volumes:
      - nexus-data:/nexus-data
      - nexus-blob:/nexus-data/blobs
    networks:
      - devops
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nexus.tls=true'
      - 'traefik.http.routers.nexus.rule=Host(`nexus.docker.internal`)'
      - 'traefik.http.routers.nexus.entrypoints=websecure'
      - 'traefik.http.services.nexus.loadbalancer.server.port=8080'
      - 'traefik.docker.network=devops'
    networks:
      - devops

networks:
  devops:
    external: true

volumes:
  nexus-data: {}
  nexus-blob: {}
