version: '3'
services:
  sonarqube:
    image: sonarqube:8.2-community
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/data:/opt/sonarqube/data
      # - ./sonarqube/extensions:/opt/sonarqube/extensions

    labels:
      - 'traefik.http.routers.sonarqube.tls=true'
      - 'traefik.http.routers.sonarqube.rule=Host(`sonarqube.docker.internal`)'
      - 'traefik.http.routers.sonarqube.entrypoints=websecure'
      - 'traefik.http.services.sonarqube.loadbalancer.server.port=9000'

networks:
  default:
    external: true
    name: devops
