version: '3'
services:
  sonarqube:
    image: sonarqube:8.2-community
    # ports:
    #   - 9000:9000
    volumes:
      - ${PWD}/data:/opt/sonarqube/data
      # - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - devops
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarqube.rule=Host(`sonarqube.docker.internal`)'
      - 'traefik.http.routers.sonarqube.entrypoints=websecure'
      - 'traefik.http.services.sonarqube.loadBalancer.services.address=sonarqube:9000'
      - 'traefik.docker.network=devops'

networks:
  devops:
    external: true 
