# Infrastructure Storage Layer
# 此層包含所有儲存相關的基礎設施服務

services:
  # PostgreSQL - 關聯式資料庫
  postgres:
    extends:
      file: ./postgres/docker-compose.yml
      service: postgres

  # pgAdmin - PostgreSQL 管理界面
  pgadmin:
    extends:
      file: ./postgres/docker-compose.yml
      service: pgadmin

  # Redis - 快取和訊息佇列
  redis:
    extends:
      file: ./redis/docker-compose.yml
      service: redis

  # Redis Commander - Redis 管理界面
  redis-commander:
    extends:
      file: ./redis/docker-compose.yml
      service: redis-commander

volumes:
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data
  redis_data:
    name: redis_data

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK:-devops}