

# Infrastructure Security Layer
# 此層包含所有安全相關的基礎設施服務

services:
  # Keycloak - 身份認證和授權管理
  keycloak:
    extends:
      file: ./keycloak/docker-compose.yml
      service: keycloak

volumes:
  keycloak_data:
    name: keycloak_data

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK:-devops}