version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.6.2-alpine
    # restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.routers.portainer.rule=HostRegexp(`portainer.$MY_DOMAIN`)'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

volumes:
  portainer_data: {}
