
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ports:
    #   - 3306:3306
    labels:
      - 'traefik.tcp.routers.mysql.rule=Host(`mysql.$MY_DOMAIN`)'
      - 'traefik.tcp.routers.mysql.entrypoints=mysql'
      - 'traefik.tcp.routers.mysql.service=mysql'
      - 'traefik.tcp.services.mysql.loadBalancer.server.port=3306'
