version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.72.1
    #   - 5678:5678
    labels:
    - 'traefik.http.routers.n8n.tls=true'
    - 'traefik.http.routers.n8n.rule=Host(`n8n.$MY_DOMAIN`)'
    - 'traefik.http.routers.n8n.entrypoints=websecure'
    - 'traefik.http.services.n8n.loadbalancer.server.port=5678'
    volumes:
    - ${HOME}/.n8n:/home/node/.n8n
    environment:
    - N8N_HOST=n8n.docker.internal
