version: '3'

services:
  server:
    image: gitea/gitea:latest
    # container_name: gitea
    hostname: gitea.docker.internal
    environment:
      - USER_UID=1000
      - USER_GID=1000
    # restart: always
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.http.routers.gitea.tls=true'
      - 'traefik.http.routers.gitea.rule=Host(`gitea.$MY_DOMAIN`)'
      - 'traefik.http.routers.gitea.entrypoints=websecure'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
    ports:
      - '9922:22'

volumes:
  gitea-data: {}
