version: '3'
services:
  keycloak:
    image: jboss/keycloak:14.0.0
    hostname: keycloak.docker.internal
    environment:
      - 'KEYCLOAK_USER=keycloak'
      - 'KEYCLOAK_PASSWORD=keycloak'
      - 'PROXY_ADDRESS_FORWARDING=true'
      - 'DB_VENDOR=postgres'
      - 'DB_ADDR=postgres'
      - 'DB_USER=keycloak'
      - 'DB_PASSWORD=keycloak'
    #   INSTALL4J_ADD_VM_PARAMS: -Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g
    # volumes:
    #   - ./deployments:/opt/jboss/keycloak/standalone/deployments
    #ports:
    #  - 8080:8080/tcp
    # command: ./standard
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.keycloak.tls=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.docker.internal`)'
      - 'traefik.http.routers.keycloak.entrypoints=websecure'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.name=keycloak_sticky'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.secure=true'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.httpOnly=true'
      - 'traefik.docker.network=devops'

    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=keycloak'

volumes:
  postgres_data: {}

networks:
  default:
    external:
      name: devops
