version: '3'
services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - 'KEYCLOAK_USER=keycloak'
      - 'KEYCLOAK_PASSWORD=keycloak'
      - 'PROXY_ADDRESS_FORWARDING=true'
      - 'DB_VENDOR=postgres'
    #   INSTALL4J_ADD_VM_PARAMS: -Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g
    # volumes:
    #   - ./deployments:/opt/jboss/keycloak/standalone/deployments
    #ports:
    #  - 8080:8080/tcp
    # command: ./standard
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.docker.internal`)'
      - 'traefik.http.routers.keycloak.entrypoints=web'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
      - 'traefik.docker.network=devops'
    networks:
      - devops
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - devops

volumes:
  postgres_data:

networks:
  devops:
    external: true
