version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    # platform: linux/amd64
    hostname: keycloak.docker.internal
    command: start-dev
    environment:
      - 'KEYCLOAK_admin=keycloak'
      - 'KEYCLOAK_ADMIN_PASSWORD=keycloak'
      # - 'KEYCLOAK_USER=keycloak'
      # - 'KEYCLOAK_PASSWORD=keycloak'
      - 'PROXY_ADDRESS_FORWARDING=true'
      - 'DB_VENDOR=postgres'
      - 'DB_ADDR=postgres'
      - 'DB_USER=keycloak'
      - 'DB_PASSWORD=keycloak'
    #   INSTALL4J_ADD_VM_PARAMS: -Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g
    # volumes:
    #   - ./deployments:/opt/jboss/keycloak/standalone/deployments
    #ports:
    #  - 8080:8080/tcp
    # command: ./standard
    labels:
      - 'traefik.http.routers.keycloak.tls=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.$MY_DOMAIN`)'
      - 'traefik.http.routers.keycloak.entrypoints=websecure'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.name=keycloak_sticky'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.secure=true'
      - 'traefik.http.services.keycloak.loadbalancer.sticky.cookie.httpOnly=true'
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=keycloak'

volumes:
  postgres_data: {}
