version: '3'

services:
  traefik:
    image: 'traefik:3.2.1'
    command:
    - '--log.level=INFO'
    - '--global.checkNewVersion=true'
    - '--providers.docker=true'
    - '--providers.docker.exposedbydefault=true'
    - '--entrypoints.web.address=:80'
    - '--entrypoints.websecure.address=:443'
    - '--entrypoints.mysql.address=:3306/tcp'
    - '--entrypoints.postgres.address=:5432/tcp'
    - '--api.insecure=true' # Allow insecure API for development
    - '--api.dashboard=true'
    - '--providers.file.directory=/etc/traefik/dynamic_conf'
    - '--providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.docker.internal`)'
    labels:
    - 'traefik.http.routers.traefik.tls=true'
    - 'traefik.http.routers.traefik.rule=HostRegexp(`traefik.$MY_DOMAIN`)'
    - 'traefik.http.routers.traefik.entrypoints=websecure'
    - 'traefik.http.routers.traefik.service=api@internal'
    - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
    - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
    - 'traefik.http.routers.http-catchall.entrypoints=web'
    - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker'
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '/etc/localtime:/etc/localtime:ro'
    - './certs:/certs'
    - './conf:/etc/traefik/dynamic_conf:ro'
    - './logs:/var/log/traefik'

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
    - 'traefik.http.routers.whoami.entrypoints=websecure'
    - 'traefik.http.routers.whoami.tls=true'
