global:
  checkNewVersion: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true
    defaultRule: "Host(`{{ normalize .Name }}.docker.internal`)"
  file:
    watch: true
    directory: /etc/traefik/dynamic_conf
api:
  insecure: true
  dashboard: true
log:
  level: INFO