version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    # ports:
    # - "5672:5672"
    container_name: rabbitmq
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=devops'
      # web browser access to RabbitMQ management GUI
      - 'traefik.http.routers.rabbitmq-mgr.tls=true'
      - 'traefik.http.routers.rabbitmq-mgr.rule=Host(`rabbitmq-management.docker.internal`)'
      - 'traefik.http.routers.rabbitmq-mgr.entrypoints=websecure'
      - 'traefik.http.services.rabbitmq-mgr.loadbalancer.server.port=15672'
      # AMQPS - SSL terminated by traefik (over 443, not 5672)
      - 'traefik.tcp.routers.rabbitmq.tls=true'
      - 'traefik.tcp.routers.rabbitmq.rule=HostSNI(`rabbitmq.docker.internal`)'
      - 'traefik.tcp.routers.rabbitmq.entrypoints=websecure'
      - 'traefik.tcp.services.rabbitmq.loadbalancer.server.port=5672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./enable_plugins:/etc/rabbitmq/enable_plugins:ro

volumes:
  rabbitmq: {}

networks:
  default:
    external:
      name: devops
