version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.docker.internal
    # ports:
    # - '80:80'
    # - '8443:443'
    # - '8822:22'
    environment:
      - 'EXTERNAL_URL=https://gitlab.docker.internal/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitlab.tls=true'
      - 'traefik.http.routers.gitlab.rule=HostRegexp(`gitlab.docker.internal`)'
      - 'traefik.http.routers.gitlab.entrypoints=websecure'
      - 'traefik.http.services.gitlab.loadbalancer.server.port=80'
      - 'traefik.docker.network=devops'
    volumes:
      - gitlab-config:/etc/gitlab 
      - gitlab-data:/var/opt/gitlab
    networks:
      - devops
  runner:
    image: gitlab/gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./runner/config:/etc/gitlab-runner
    networks:
      - devops

networks:
  devops:
    external: true

volumes:
  gitlab-config: {} 
  gitlab-data: {}