version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:14.1.2-ce.0
    hostname: gitlab.docker.internal
    ports:
      # - '80:80'
      # - '8443:443'
      - '8822:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    labels:
      - 'traefik.http.routers.gitlab.tls=true'
      - 'traefik.http.routers.gitlab.rule=Host(`gitlab.$MY_DOMAIN`)'
      - 'traefik.http.routers.gitlab.entrypoints=websecure'
      - 'traefik.http.services.gitlab.loadbalancer.server.port=80'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
  runner:
    image: gitlab/gitlab-runner:alpine-v14.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - gitlab-runner:/etc/gitlab-runner

volumes:
  gitlab-config: {}
  gitlab-data: {}
  gitlab-runner: {}

configs:
  gitlab:
    file: ./gitlab.rb
