version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    # restartPolicy: always
    hostname: gitlab
    # ports:
      # - '80:80'
      # - '8443:443'
      # - '8822:22'
    environment:
      - 'EXTERNAL_URL=http://gitlab.internal.local/'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.internal.local`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.docker.network=devops"
    volumes:
      - ./storage/config:/etc/gitlab
      - ./storage/logs:/var/log/gitlab
      - ./storage/data:/var/opt/gitlab
    networks:
      - devops
  runner:
    image: gitlab/gitlab-runner
    # restartPolicy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner/config:/etc/gitlab-runner
    networks:
      - devops

networks:
  devops:
    external: true
