version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.docker.internal
    ports:
      # - '80:80'
      # - '8443:443'
      - '8822:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitlab.tls=true'
      - 'traefik.http.routers.gitlab.rule=Host(`gitlab.docker.internal`)'
      - 'traefik.http.routers.gitlab.entrypoints=websecure'
      - 'traefik.http.services.gitlab.loadbalancer.server.port=80'
      - 'traefik.docker.network=$DEFAULT_NETWORK'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
  runner:
    image: gitlab/gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./runner/config:/etc/gitlab-runner

networks:
  default:
    external:
      name: $DEFAULT_NETWORK

volumes:
  gitlab-config: {}
  gitlab-data: {}

configs:
  gitlab:
    file: ./gitlab.rb
