version: '3'
services:
  server:
    image: jboss/jbpm-server-full:latest
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    labels:
      - 'traefik.http.routers.jbpm.rule=Host(`jbpm.docker.internal`)'
      - 'traefik.http.routers.jbpm.entrypoints=web'
      - 'traefik.http.services.jbpm.loadbalancer.server.port=8080'

    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: devops
