# 共用中間件定義
http:
  middlewares:
    # 基本認證中間件
    basic-auth:
      basicAuth:
        users:
          # admin:admin (使用 htpasswd 生成)
          - "admin:$2y$10$ruca7bMqHMWwbfkCKMsZ2ejIxqyS9HlGPa5tFZzw.I6JGfIYbgOGq"

    # 安全標頭中間件
    security-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"

    # Rate Limiting 中間件
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    # 壓縮中間件
    compression:
      compress: {}

    # CORS 中間件
    cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 86400
        addVaryHeader: true

    # 開發環境專用 - 允許不安全的連線
    dev-headers:
      headers:
        customResponseHeaders:
          X-Dev-Environment: "true"
        accessControlAllowOriginList:
          - "*"