# TLS 配置
tls:
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

    modern:
      minVersion: "VersionTLS13"

  # 本地開發用的自簽憑證
  certificates:
    - certFile: /certs/local-cert.pem
      keyFile: /certs/local-key.pem
      stores:
        - default

# 通配符憑證 store
stores:
  default:
    defaultCertificate:
      certFile: /certs/local-cert.pem
      keyFile: /certs/local-key.pem