version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    hostname: jenkins.docker.internal
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      # add docker cloud support
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
    # ports:
    # - 8080:8080
    # - 50000:50000
    labels:
      - 'traefik.http.routers.jenkins.tls=true'
      - 'traefik.http.routers.jenkins.rule=Host(`jenkins.docker.internal`)'
      - 'traefik.http.routers.jenkins.entrypoints=websecure'
      - 'traefik.http.services.jenkins.loadbalancer.server.port=8080'

volumes:
  jenkins_home: {}

networks:
  default:
    external: true
    name: devops
