services:
  registry:
    image: registry:2.8
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml  # 配置檔案
      - ./data:/var/lib/registry                     # 緩存目錄
    ports:
      - "5000:5000"
  nginx:
    image: nginx:stable
    hostname: nexus.docker.internal
    # ports:
    # - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - 'traefik.http.routers.registry.tls=true'
      - 'traefik.http.routers.registry.rule=Host(`registry.$MY_DOMAIN`)'
      - 'traefik.http.routers.registry.entrypoints=websecure'
      - 'traefik.http.services.registry.loadbalancer.server.port=80'