version: '2.3'
services:
  log:
    image: goharbor/harbor-log:v1.10.2
    container_name: harbor-log
    restart: always
    dns_search: .
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - ./logs/:/var/log/docker/:z
      - type: bind
        source: ./common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
      - type: bind
        source: ./common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - devops
  registry:
    image: goharbor/registry-photon:v1.10.2
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./data/secret/registry/root.crt
        target: /etc/registry/root.crt
    networks:
      - devops
    dns_search: .
    depends_on:
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'registry'
  registryctl:
    image: goharbor/harbor-registryctl:v1.10.2
    container_name: registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
    networks:
      - devops
    dns_search: .
    depends_on:
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'registryctl'
  postgresql:
    image: goharbor/harbor-db:v1.10.2
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - ./data/database:/var/lib/postgresql/data:z
    networks:
      - devops
    dns_search: .
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'postgresql'
  core:
    image: goharbor/harbor-core:v1.10.2
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - ./data/ca_download/:/etc/core/ca/:z
      - ./data/psc/:/etc/core/token/:z
      - ./data/:/data/:z
      - ./common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: ./data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: ./data/secret/keys/secretkey
        target: /etc/core/key
    networks:
      - devops
    dns_search: .
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'core'
  portal:
    image: goharbor/harbor-portal:v1.10.2
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    networks:
      - devops
    dns_search: .
    depends_on:
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'portal'

  jobservice:
    image: goharbor/harbor-jobservice:v1.10.2
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./data/job_logs:/var/log/jobs:z
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
    networks:
      - devops
    dns_search: .
    depends_on:
      - core
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'jobservice'
  redis:
    image: goharbor/redis-photon:v1.10.2
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./data/redis:/var/lib/redis
    networks:
      - devops
    dns_search: .
    depends_on:
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'redis'
  proxy:
    image: goharbor/nginx-photon:v1.10.2
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - devops
    dns_search: .
    ports:
      - 80:8080
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'tcp://127.0.0.1:1514'
        tag: 'proxy'
networks:
  devops:
    external: true
