concurrent = 4
check_interval = 10
log_level = "debug"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "sample-runner"
  url = "http://gitlab/"
  token = "6-2v58syLAoirnX34ZuY"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "docker-runner"
  url = "http://gitlab/"
  token = "p1LsQi7s_SSRhi4yTws6"
  executor = "docker"
  cache_dir = "/mnt/docker_cache"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "busybox:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = true
    disable_cache = false
    volumes = ["/cache", "/root/.m2/repository"]
    shm_size = 0
    network_mode = "gitlab-test"
