concurrent = 4
check_interval = 10
log_level = "debug"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-docker-runner"
  url = "http://gitlab.docker.internal"
  token = "UFAtAWYL8TYiLLLxV8nK"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/root/.m2/repository"]
    shm_size = 0
