version: '3.8'

# Infrastructure Network Layer
# 此層包含所有網路相關的基礎設施服務

services:
  # Traefik - 反向代理和負載平衡器
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik

  # Whoami - Traefik 測試服務
  whoami:
    extends:
      file: ./traefik/docker-compose.yml
      service: whoami

  # DNSmasq - 本地 DNS 服務
  dnsmasq:
    extends:
      file: ./dnsmasq/docker-compose.yml
      service: dnsmasq
    depends_on:
      - traefik

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK:-devops}

volumes:
  letsencrypt:
    name: letsencrypt